### ISSUE TITLE
Issue with downloading https://github.com/thecodefactory/libbitcoin-explorer

### ISSUE THREAD

**Issue by skaht** [libbitcoin/libbitcoin-explorer#277]
See https://github.com/libbitcoin/libbitcoin-explorer/blob/master/install.sh#L609

Line 609 first performs a download such as:

`git clone --branch bip-38 --single-branch https://github.com/thecodefactory/libbitcoin-explorer`

Please see if the command above is working properly.  "--branch bip-38" isn't found at this end.

After performing a `git clone https://github.com/thecodefactory/libbitcoin-explorer.git`

    % git branch -a
    * master
      remotes/origin/HEAD -> origin/master
      remotes/origin/bip-39
      remotes/origin/master
      remotes/origin/version2

Notice there is a bip-39, not a bip-38.

**Comment by thecodefactory** [comment]
Thanks for giving it a try, but it was merged into master and I deleted my branch.  You could try my master branch instead (should be close to sync'd with libbitcoin master).  It should work for mainnet with icu, but not sure other configurations will work (i.e. testnet or no icu) since it required a libbitcoin pr as well that wasn't merged.  @evoskuil is heavily refactoring it, so it may be best to sync up with him if you want the latest, but if you do end up testing that out, let me know how it goes, thanks!

**Comment by thecodefactory** [comment]
Oh, and install.sh should now point to libbitcoin instead of thecodefactory for both libbitcoin and libbitcoin-explorer.

**Comment by skaht** [comment]
Yep,  Eric probably needs to tweak both the repo and the branch for https://github.com/libbitcoin/libbitcoin-explorer/blob/master/install.sh#L609.

**Comment by thecodefactory** [comment]
Ok, I just did -- give it a go now.

**Comment by skaht** [comment]
After the tweak was made, I confirmed the fix works (compiled and tested) for my homegrown build script for libbitcoin-explorer when the following merged master branch is applied :-)

master 288866e Merge pull request #269 from thecodefactory/bip-38

**Comment by thecodefactory** [comment]
Great news, thanks!

**Comment by skaht** [comment]
The Autotools has its place for enabling code portability, but it makes setting up a development environment painful for someone that hasn't seriously coded in over 16 years. I'm trying to set up a bx debugging project within Xcode on a Mac.  If I can get a minimalist non-portable Makefile established, that will contain the core information I need to initialize the Xcode IDE bx project.

Reverse engineering scripts built from automation to create a minimalist Makefile is very painful. Any chance you can give me a hand for determining the final linking that goes on to make bx?  All I'm looking for are the small hand full of lines required to finish the linking to a main() in the compiled bx executable.  I can already compile the 100+ *.lo and *o files in a Makefile using libtool.  Just need to link them and with the associated dependency libraries.  I'm guessing the console/main.cpp is the main used for the bx command line tool?

This will allow me to be more proactive at identifying issues along with candidate fixes on a Mac Platform.  After I get bx under my belt, I plan to do the same for bs.

**Comment by evoskuil** [comment]
@skaht I don't get under the covers too much with the build. I spent a lot of time getting on top of the autotools (with libbitcoin-build) but what they do internally is beyond my patience level to muck with. I did go through what you are doing in Xcode, but with Visual Studio. Basically just created a project and added the sources, then worked on the breaks and dependencies. You shouldn't have breaks, since we already support clang and osx, and the dependencies are well-defined.

I would consider, once you have something working, constructing the Xcode project files via libbitcoin-build. All of the non-VS builds are currently constructed this way. I'm planning to do this as well for VS, which won't be that hard now that I have it done for Autotools builds (it's done for bx but not the others). Doing the same for XCode should be straightforward. I would probably tackle this at the same time as the VS work.

**Comment by skaht** [comment]
I'm very old school... I plan to leave the source code in the native directories the libbitcoin configures create.  Just need to effectively instruct Xcode through its GUI what the core bx files are, and associated -D, -I and -Ls that are required.  Will have to experiment to see if Xcode can handle glibtool versus the libtool that comes bundled with the Mac OS. Will also have to determine if the Mac can natively handle GNU *.pc package files.

**Comment by evoskuil** [comment]
Sure, that's exactly what I'm talking about, and how it works with VS.
