### ISSUE TITLE
All commands seg fault, manual build [osx]

### ISSUE THREAD

**Issue by alexreg** [libbitcoin/libbitcoin-explorer#335]
`bx` and `bx [command] --help` seem to run fine though. 

I built the version2 branch.

**Comment by evoskuil** [comment]
All commands?

**Comment by alexreg** [comment]
It seems like it yes.

**Comment by evoskuil** [comment]
Assuming you built with `install.sh` could you post your command line and OS so I can repro?

**Comment by alexreg** [comment]
I built manually. OS is OS X 10.11.4.

**Comment by evoskuil** [comment]
Okay, I don't expect an issue as I've previously built bx/version2 on OSX (for the release binaries). But I'm running a build now.

**Comment by evoskuil** [comment]
The problem did not repro for me.

**Comment by evoskuil** [comment]
```
[18:28] <Noldorin> evoskuil, FYI here's the log of my last (manual) build of libbitcoin-explorer. http://hastebin.com/ocusosipiy
```
The manual build log for bx alone doesn't show any problems. There's not much to go on without a repro. A stack trace would be helpful.

I see you set the `--with-icu` option. The ICU dependency is difficult, as boost conditionally depends on it and has a bug in its ICU detection. The installer has a workaround for that. I would need to see the boost build log to see that issue.

RE: manual build - the `--with-icu` option is actually applied in the `libbitcoin` build and picked up in the package config by `explorer`. The explorer installer accepts the option because it builds libbitcoin.
```
[20:03] <Noldorin> evoskuil, unfortunately building using the install.sh script and --disable-shared --build-boost gives this error :( http://hastebin.com/aruxipegeq
```
The errors indicate a failure to link `boost_regex`. It would be most helpful if you posted the entire build log for the install.sh. That would show me whether it was built and how it was located and linked.

**Comment by alexreg** [comment]
Here’s the (very long) log for the the boost build (MacPorts):

https://cloudup.com/cVegQpxTmww

And here’s the complete log for the `install.sh` build.

http://hastebin.com/oyudofukux

**Comment by alexreg** [comment]
Okay, so I’ve got the `./install.sh` build working now. The segfault occurs with this too however, under the same conditions. The results of `make check` could prove interesting however, since this fails:

http://hastebin.com/ezufexilol

**Comment by evoskuil** [comment]
The link errors show that boost test is missing. The installer console out has the necessary information to troubleshoot, including an abbreviated boost build log.

**Comment by evoskuil** [comment]
@alexreg I believe this was resolved as the boost cross-linking I described above. Would you please confirm/close or update? Thanks!

**Comment by alexreg** [comment]
Yes, it was indeed resolved. Cross-linking and mixing compilers (GCC and clang) seemed to be the core problems.

Thanks for your help.
