### ISSUE TITLE
mnemonic-to-seed produces seed not equivalent to original

### ISSUE THREAD

**Issue by atweiden** [libbitcoin/libbitcoin-explorer#366]
Using the [BX 2.2.0 stable release](https://aur.archlinux.org/packages/libbitcoin-explorer):

```sh
#!/bin/bash
_seed=$(bx seed -b 128)
_mnem=$(bx mnemonic-new $_seed)
echo $_seed # bc9a1cec489cb6582652b4fc774aabc3
echo $_mnem # route special deposit muffin slice clown off final wise ripple priority margin

_rseed=$(bx mnemonic-to-seed $_mnem)
echo $_rseed # 57e5a8c3b4ed02b6c23ee8e14ce67dd091dcd5c06dd637fa378f5d42e770a17860642b7bc28fb4917a7bfd92a6b97cf13cf5b4ce3c636062ca508ffd6dc842d9

_hd=$(bx hd-new $_seed)
echo $_hd # xprv9s21ZrQH143K38iNL5rCBVQgudcwPjFBLsFvc9v1UJbZn3orMnQ8jWCDvxAiUQaggH23Cfcz9BHb3ac9ZWLsnz2gj6si5Q5omAUTQ5uGPNR
_rhd=$(bx hd-new $_rseed)
echo $_rhd # xprv9s21ZrQH143K3wuy8Xe8arw7A2cwG59TGURoEXnkk8k8n27rwYSDMrPrjvhahTdmtdZ4Vpuk2rb7hxKtsdKDU4UPZAUDgmLa9eL3bhKaqqh
```

The original seed is not the same as the seed produced by `mnemonic-to-seed`.

**Comment by evoskuil** [comment]
This is correct behavior. Please review BIP-39.

**Comment by atweiden** [comment]
Right you are. I verified BX does the correct thing using bitcore as a benchmark.

So with bip39, if you lose the original seed after you generate it, it's gone? Does losing the original have any consequences?

**Comment by evoskuil** [comment]
The original seed is just a source of randomness, it cannot be obtained from the mnemonic and serves no purpose after mnemonic generation.

**Comment by lyhistory** [comment]
@evoskuil two more questions:
1) I think the early version has cmd 'mnemonic-decode' which can convert the words to the original seed, example can be found here (last two commands)https://github.com/bitcoinbook/bitcoinbook/blob/second_edition_print3_rc2/appdx-bx.asciidoc
    , do you mean for current version there is no way to convert the long numeric representation to the original seed

2) regarding to the last example in your wiki: https://github.com/libbitcoin/libbitcoin-explorer/wiki/bx-mnemonic-to-seed,
    is there any major difference between
    bx hd-new < seed.txt
    and
    bx mnemonic-new < seed.txt | bx mnemonic-to-seed | bx hd-new
    (seed.txt is the same, bx seed > seed.txt)
    these two cmd will result in different private key, not sure which one is more secure or better

**Comment by thecodefactory** [comment]
@lyhistory The old mnemonic-decode (electrum v1 mnemonics I believe) were dropped from libbitcoin before version3 and replaced with BIP-39 mnemonics.  libbitcoin version4 also adds in electrum v2 mnemonics.

Regarding 2, yes there's a difference.  Unlike electrum v1 mnemonics (which are symmetric), BIP-39 is asymmetric in the manner that you're asking about.  In short, BIP-39 mnemonics go from `entropy -> mnemonic -> seed`.  Then you can use the mnemonic by going from `mnemonic -> seed`.  The entropy is not meaningfully recreated by the mnemonic, and the entropy is not the seed.

So your example in 2 differs because you're doing:

`entropy -> hd-new` and comparing it to `entropy -> mnemonic -> seed -> hd-new` which is different.

**Comment by lyhistory** [comment]
@thecodefactory cool, thanks
