### ISSUE TITLE
Does bx support creating RBF transactions?

### ISSUE THREAD

**Issue by mosreq** [libbitcoin/libbitcoin-explorer#415]
If not, are you going to implement it sometime?

**Comment by thecodefactory** [comment]
I don't think creating RBF transactions is any different than creating normal transactions, so that part should be supported.  Are you asking if the libbitcoin-server/node accepts RBF transactions?  I don't believe that it does at this time, but @evoskuil would know better.  I'm also not aware if this is on the current roadmap.

**Comment by evoskuil** [comment]
There is no distinction in bx, make whatever you want :)

The v2 server/node may reject txs that are already spent in the mempool.
