### ISSUE TITLE
There is an error after installed with sudo ./install.sh that cannot work

### ISSUE THREAD

**Issue by WangYyyyy** [libbitcoin/libbitcoin-explorer#551]
`./install.sh `

```
Libbitcoin installer configuration.
--------------------------------------------------------------------
OS                    : Darwin
PARALLEL              : 4
CC                    : clang
CXX                   : clang++
CPPFLAGS              : 
CFLAGS                : 
CXXFLAGS              : 
LDFLAGS               : 
LDLIBS                : 
WITH_ICU              : 
WITH_PNG              : 
WITH_QRENCODE         : 
BUILD_ICU             : 
BUILD_ZLIB            : 
BUILD_PNG             : 
BUILD_QRENCODE        : 
BUILD_ZMQ             : 
BUILD_BOOST           : 
PREFIX                : /usr/local
BUILD_DIR             : build-libbitcoin-explorer
DISABLE_SHARED        : 
DISABLE_STATIC        : 
with_boost            : 
with_pkgconfigdir     : --with-pkgconfigdir=/usr/local/lib/pkgconfig
--------------------------------------------------------------------
```

It shows successful 

```
============================================================================
Testsuite summary for libbitcoin-explorer 3.4.0
============================================================================
# TOTAL: 1
# PASS:  1
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
Running 506 test cases...
Platform: Mac OS
Compiler: Clang version 9.0.0 (clang-900.0.39.2)
STL     : libc++ version 4000
Boost   : 1.66.0

real	27m25.055s
user	60m59.967s
sys	5m47.771s
```

then I typed `bx help` or any other commands 
it always return 
`Error: can not read options configuration file ''`

**Comment by evoskuil** [comment]
That is a [boost error](https://www.boost.org/doc/libs/1_66_0/boost/program_options/errors.hpp) resulting from failure to load the configured settings file. I have not seen this so just to make sure you don't have a problem with your boost build, try installing to a `--prefix` directory with `--build-boost` and avoiding sudo. The most common errors resulting from build are from existing boost installations.

Otherwise you can also explicitly specify a config file path on the bx command line. This may avoid the error, however the file should not be required. More info [here](https://github.com/libbitcoin/libbitcoin-explorer/wiki/Configuration-Settings).

**Comment by WangYyyyy** [comment]
Thank you for pointed out where the error occurred, reinstall boost then it worked
