### ISSUE TITLE
generate address from electrum seed

### ISSUE THREAD

**Issue by bitdaric** [libbitcoin/libbitcoin-explorer#623]
I am trying to generate electrum wallet address using bx tool (standard wallet, p2pkh ) but getting different results (addresses):

```
bx mnemonic-to-seed 12_words_electrum_seed_here | bx hd-new | bx hd-public -i0 | bx hd-public -i0 | bx hd-to-ec | bx ec-to-address
WARNING: The specified words are not a valid mnemonic in any supported dictionary.
1JDmLLxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

but first address in electrum is:
`1M37Mxxxxxxxxxxxxxxxxxxxxxxxxxxxxx`

**Comment by thecodefactory** [comment]
Look up `bx electrum-new` and `bx electrum-to-seed` commands.  The `mnemonic-to-seed` command is for BIP39 mnemonics.  The warning above is because one (or more) of the words specified is not valid (i.e. present) in the mnemonic dictionary.  In electrum, it can be used anyway, but make sure that you're using an electrum 2.x mnemonic, as 1.x mnemonics are no longer supported.
